COMPONENT=MultihopOscilloscopeAppC
CFLAGS += -I$(TOSDIR)/lib/net/ -I$(TOSDIR)/lib/net/ctp  -I$(TOSDIR)/lib/net/4bitle

# To change the transmit power
#CFLAGS += -DCC2420_DEF_RFPOWER=31
include $(MAKERULES)
